/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/Account/RefreshToken': {
    post: operations['RefreshToken']
  }
  '/Account/GetUserData': {
    get: operations['GetCurrentUserAccount']
  }
  '/Account/UpdateUserData/{id}': {
    put: operations['UpdateCurrentUserAccount']
  }
  '/Account/SignUp': {
    post: operations['SignUp']
  }
  '/Account/ResendVerificationEmail': {
    post: operations['ResendVerificationEmail']
  }
  '/Account/ReSendOtpCode': {
    post: operations['ReSendOtpCode']
  }
  '/Account/ConfirmOTP': {
    post: operations['ConfirmOTP']
  }
  '/Account/VerifyEmail': {
    post: operations['VerifyEmail']
  }
  '/Account/SignIn': {
    post: operations['SignIn']
  }
  '/Account/GoogleLogin': {
    post: operations['GoogleLogin']
  }
  '/Account/ForgetPassword': {
    post: operations['ForgetPassword']
  }
  '/Account/ResetPassword': {
    post: operations['ResetPassword']
  }
}

export interface components {
  schemas: {
    ConfirmEmailForm: {
      email?: string | null
      token?: string | null
    }
    ConfirmOTPForm: {
      username: string
      otp: string
    }
    ForgotPasswordForm: {
      userName: string
    }
    GoogleLoginRequest: {
      idToken?: string | null
    }
    ProblemDetails: {
      type?: string | null
      title?: string | null
      /** Format: int32 */
      status?: number | null
      detail?: string | null
      instance?: string | null
    } & { [key: string]: unknown }
    RefreshTokenForm: {
      accessToken: string
      refreshToken: string
    }
    ResetPasswordForm: {
      code: string
      userName: string
      newPassword: string
      newPasswordConfirmation: string
    }
    SignInForm: {
      userName: string
      password: string
    }
    SignUpForm: {
      userName: string
      password: string
    }
    UpdateAccountForm: {
      phoneNumber?: string | null
      /** Format: email */
      email: string
      userName?: string | null
    }
  }
}

export interface operations {
  RefreshToken: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['RefreshTokenForm']
        'application/json': components['schemas']['RefreshTokenForm']
        'text/json': components['schemas']['RefreshTokenForm']
        'application/*+json': components['schemas']['RefreshTokenForm']
      }
    }
  }
  GetCurrentUserAccount: {
    responses: {
      /** Success */
      200: unknown
    }
  }
  UpdateCurrentUserAccount: {
    parameters: {
      path: {
        id: string
      }
    }
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['UpdateAccountForm']
        'application/json': components['schemas']['UpdateAccountForm']
        'text/json': components['schemas']['UpdateAccountForm']
        'application/*+json': components['schemas']['UpdateAccountForm']
      }
    }
  }
  SignUp: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SignUpForm']
        'application/json': components['schemas']['SignUpForm']
        'text/json': components['schemas']['SignUpForm']
        'application/*+json': components['schemas']['SignUpForm']
      }
    }
  }
  ResendVerificationEmail: {
    parameters: {
      query: {
        email?: string
      }
    }
    responses: {
      /** Success */
      200: unknown
    }
  }
  ReSendOtpCode: {
    parameters: {
      query: {
        userName?: string
      }
    }
    responses: {
      /** Success */
      200: unknown
    }
  }
  ConfirmOTP: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['ConfirmOTPForm']
        'application/json': components['schemas']['ConfirmOTPForm']
        'text/json': components['schemas']['ConfirmOTPForm']
        'application/*+json': components['schemas']['ConfirmOTPForm']
      }
    }
  }
  VerifyEmail: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['ConfirmEmailForm']
        'application/json': components['schemas']['ConfirmEmailForm']
        'text/json': components['schemas']['ConfirmEmailForm']
        'application/*+json': components['schemas']['ConfirmEmailForm']
      }
    }
  }
  SignIn: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SignInForm']
        'application/json': components['schemas']['SignInForm']
        'text/json': components['schemas']['SignInForm']
        'application/*+json': components['schemas']['SignInForm']
      }
    }
  }
  GoogleLogin: {
    responses: {
      /** Error */
      default: {
        content: {
          'application/json': components['schemas']['ProblemDetails']
          'text/json': components['schemas']['ProblemDetails']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['GoogleLoginRequest']
        'application/json': components['schemas']['GoogleLoginRequest']
        'text/json': components['schemas']['GoogleLoginRequest']
        'application/*+json': components['schemas']['GoogleLoginRequest']
      }
    }
  }
  ForgetPassword: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['ForgotPasswordForm']
        'application/json': components['schemas']['ForgotPasswordForm']
        'text/json': components['schemas']['ForgotPasswordForm']
        'application/*+json': components['schemas']['ForgotPasswordForm']
      }
    }
  }
  ResetPassword: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['ResetPasswordForm']
        'application/json': components['schemas']['ResetPasswordForm']
        'text/json': components['schemas']['ResetPasswordForm']
        'application/*+json': components['schemas']['ResetPasswordForm']
      }
    }
  }
}

export interface external {}
