/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/Account/SignIn': {
    post: operations['SignIn']
  }
  '/Account/RefreshToken': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['RefreshTokenRequest']
          'application/json': components['schemas']['RefreshTokenRequest']
          'text/json': components['schemas']['RefreshTokenRequest']
          'application/*+json': components['schemas']['RefreshTokenRequest']
        }
      }
    }
  }
  '/Account/SignInByGoogle': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['SignInByGoogleRequest']
          'application/json': components['schemas']['SignInByGoogleRequest']
          'text/json': components['schemas']['SignInByGoogleRequest']
          'application/*+json': components['schemas']['SignInByGoogleRequest']
        }
      }
    }
  }
  '/Account/ReWriteUserSessions': {
    post: {
      responses: {
        /** Success */
        200: unknown
      }
    }
  }
  '/Account/Logout': {
    post: operations['Logout']
  }
  '/Account/Credits': {
    post: operations['Credits']
  }
}

export interface components {
  schemas: {
    ApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    ApiResultStatusCode:
      | 0
      | 1
      | 2
      | 3
      | 4
      | 5
      | 6
      | 7
      | 8
      | 9
      | 10
      | 11
      | 12
      | 13
      | 14
    LogoutAccountCommandResult: {
      isSuccedded?: boolean
    }
    LogoutAccountCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['LogoutAccountCommandResult']
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    PackageEnum: 1 | 2 | 3 | 11 | 12 | 13 | 100 | -1
    /**
     * Format: int32
     * @enum {integer}
     */
    PermissionType: 1 | 2
    RefreshTokenRequest: {
      accessToken?: string | null
      refreshToken?: string | null
    }
    SignInByGoogleRequest: {
      idToken?: string | null
    }
    UserCredit: {
      /** Format: int64 */
      userId?: number
      package?: components['schemas']['PackageEnum']
      permissionType?: components['schemas']['PermissionType']
      /** Format: date-time */
      expirationDateTime?: string | null
      totalCredits?: { [key: string]: number | null } | null
      usedCredits?: { [key: string]: number | null } | null
    }
    UserCreditApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['UserCredit']
    }
    UserSignInForm: {
      userName: string
      password: string
    }
  }
}

export interface operations {
  SignIn: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['UserSignInForm']
        'application/json': components['schemas']['UserSignInForm']
        'text/json': components['schemas']['UserSignInForm']
        'application/*+json': components['schemas']['UserSignInForm']
      }
    }
  }
  Logout: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['LogoutAccountCommandResultApiResult']
        }
      }
    }
  }
  Credits: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['UserCreditApiResult']
        }
      }
    }
  }
}

export interface external {}
