/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/Profile/Follow': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['FollowCompany']
          'application/json': components['schemas']['FollowCompany']
          'text/json': components['schemas']['FollowCompany']
          'application/*+json': components['schemas']['FollowCompany']
        }
      }
    }
  }
  '/Profile/SetActivity': {
    put: operations['SetActivity']
  }
  '/Profile/SetInformation': {
    put: operations['SetInformation']
  }
  '/Profile/SetSocialNetwork': {
    put: operations['SetSocialNetwork']
  }
  '/Profile/SetPassword': {
    put: operations['SetPassword']
  }
  '/Profile/GetUserProfileByUserId': {
    put: operations['GetUserProfileByUserId']
  }
  '/Profile/FollowNationalCode': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['FollowNationalCode']
          'application/json': components['schemas']['FollowNationalCode']
          'text/json': components['schemas']['FollowNationalCode']
          'application/*+json': components['schemas']['FollowNationalCode']
        }
      }
    }
  }
  '/Profile/FollowPostalCode': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['FollowPostalCode']
          'application/json': components['schemas']['FollowPostalCode']
          'text/json': components['schemas']['FollowPostalCode']
          'application/*+json': components['schemas']['FollowPostalCode']
        }
      }
    }
  }
  '/Profile/FollowBrand': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['FollowBrand']
          'application/json': components['schemas']['FollowBrand']
          'text/json': components['schemas']['FollowBrand']
          'application/*+json': components['schemas']['FollowBrand']
        }
      }
    }
  }
  '/Profile/UnFollow': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['UnFollowCompany']
          'application/json': components['schemas']['UnFollowCompany']
          'text/json': components['schemas']['UnFollowCompany']
          'application/*+json': components['schemas']['UnFollowCompany']
        }
      }
    }
  }
  '/Profile/UnFollowByFollowId': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['ApiResult']
          }
        }
      }
      requestBody: {
        content: {
          'application/json-patch+json': components['schemas']['UnFollowByFollowId']
          'application/json': components['schemas']['UnFollowByFollowId']
          'text/json': components['schemas']['UnFollowByFollowId']
          'application/*+json': components['schemas']['UnFollowByFollowId']
        }
      }
    }
  }
  '/Profile/GetFollowListByUserId': {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['GetFollowListByUserIdQueryResultApiResult']
          }
        }
      }
    }
  }
  '/Profile/GetActiveSessions': {
    get: operations['GetActiveSessions']
  }
  '/Profile/GetActiveSessionsByUserInfo': {
    post: operations['GetActiveSessionsByUserInfo']
  }
  '/Profile/AddToNewsLetter': {
    post: operations['AddToNewsLetter']
  }
  '/Profile/TerminateSessions': {
    delete: operations['TerminateSessions']
  }
  '/Profile/TerminateAllSessions': {
    delete: operations['TerminateAllSessions']
  }
  '/Profile/TerminateUserSessionByUserInfo': {
    delete: operations['TerminateUserSessionByUserInfo']
  }
  '/Profile/GetSavedGraphList': {
    get: operations['GetSavedGraphList']
  }
  '/Profile/SaveGraph': {
    post: operations['SaveGraph']
  }
  '/Profile/RemoveSavedGraph': {
    delete: {
      parameters: {
        query: {
          /** ممد شناسه گراف اینجا وارد کن باشه ؟ :D */
          id?: number
        }
      }
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['RemoveSavedGraphCommandResultApiResult']
          }
        }
      }
    }
  }
  '/Profile/GetSavedSearchList': {
    get: operations['GetSavedSearchList']
  }
  '/Profile/SaveSearch': {
    post: operations['SaveSearch']
  }
  '/Profile/RemoveSavedAdvancedSearch': {
    delete: {
      parameters: {
        query: {
          /** ممد شناسه جستجو اینجا وارد کن باشه ؟ :D */
          id?: number
        }
      }
      responses: {
        /** Success */
        200: {
          content: {
            'application/json': components['schemas']['RemoveSavedAdvancedSearchCommandResultApiResult']
          }
        }
      }
    }
  }
}

export interface components {
  schemas: {
    AddToNewsLetter: {
      email?: string | null
    }
    ApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    ApiResultStatusCode:
      | 0
      | 1
      | 2
      | 3
      | 4
      | 5
      | 6
      | 7
      | 8
      | 9
      | 10
      | 11
      | 12
      | 13
      | 14
    Follow: {
      /** Format: int32 */
      id?: number
      events?: components['schemas']['IDomainEvent'][] | null
      /** Format: int64 */
      userId?: number
      /** Format: int64 */
      entityId?: number
      /** Format: date-time */
      insertDate?: string
      /** Format: int32 */
      entityTypeId?: number
      entityText?: string | null
    }
    FollowBrand: {
      entityText?: string | null
    }
    FollowCompany: {
      /** Format: int64 */
      companyId?: number
    }
    FollowNationalCode: {
      /** Format: int64 */
      nationalCode?: number
    }
    FollowPostalCode: {
      /** Format: int64 */
      postalCode?: number
    }
    /**
     * Format: int32
     * @enum {integer}
     */
    Gender: 1 | 2
    GetActiveSessionsQueryResult: {
      currentSession?: components['schemas']['SessionInfoSummary']
      otherSessions?: components['schemas']['SessionInfoSummary'][] | null
    }
    GetActiveSessionsQueryResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['GetActiveSessionsQueryResult']
    }
    GetFollowListByUserIdQueryResult: {
      followList?: components['schemas']['Follow'][] | null
    }
    GetFollowListByUserIdQueryResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['GetFollowListByUserIdQueryResult']
    }
    GetSavedGraphListQueryResult: {
      userSavedGraphSummary?:
        | components['schemas']['UserSavedGraphSummary'][]
        | null
    }
    GetSavedGraphListQueryResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['GetSavedGraphListQueryResult']
    }
    GetSavedSearchListQueryResult: {
      userSavedSearchSummary?:
        | components['schemas']['UserSavedSearchSummary'][]
        | null
    }
    GetSavedSearchListQueryResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['GetSavedSearchListQueryResult']
    }
    GetUserProfileByUserIdQueryResult: {
      data?: components['schemas']['Profile']
    }
    IDomainEvent: { [key: string]: unknown }
    InsertAdvancedSearchHistoryDto: {
      searchHistoryName?: string | null
      url?: string | null
    }
    InsertGraphHistoryDto: {
      name?: string | null
      json?: string | null
      /** Format: int64 */
      entityId?: number
      category?: string | null
    }
    Profile: {
      /** Format: int64 */
      id?: number
      events?: components['schemas']['IDomainEvent'][] | null
      /** Format: int64 */
      userId?: number
      /** Format: date-time */
      brithDate?: string | null
      gender?: components['schemas']['Gender']
      education?: string | null
      currentCompany?: string | null
      categoryWork?: string | null
      identificationMethod?: string | null
      /** Format: int32 */
      countCompanyPersonnel?: number | null
      instagram?: string | null
      linkdein?: string | null
      twitter?: string | null
      password?: string | null
    }
    RemoveSavedAdvancedSearchCommandResult: {
      message?: string | null
      isSuccedded?: boolean
    }
    RemoveSavedAdvancedSearchCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['RemoveSavedAdvancedSearchCommandResult']
    }
    RemoveSavedGraphCommandResult: {
      message?: string | null
      isSuccedded?: boolean
    }
    RemoveSavedGraphCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['RemoveSavedGraphCommandResult']
    }
    SaveGraphCommandResult: {
      isSuccedded?: boolean
      message?: string | null
    }
    SaveGraphCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['SaveGraphCommandResult']
    }
    SaveSearchCommandResult: {
      isSuccedded?: boolean
      message?: string | null
    }
    SaveSearchCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['SaveSearchCommandResult']
    }
    SessionDevice: {
      family?: string | null
      model?: string | null
      brand?: string | null
      isSpider?: boolean
    }
    SessionInfoSummary: {
      id?: string | null
      userAgent?: string | null
      ip?: string | null
      /** Format: date-time */
      loginDate?: string
      device?: components['schemas']['SessionDevice']
      operatingSystem?: components['schemas']['SessionOperatingSystem']
      isActive?: boolean
    }
    SessionOperatingSystem: {
      family?: string | null
      major?: string | null
      minor?: string | null
      patch?: string | null
      patchMinor?: string | null
    }
    SetActivityDto: {
      currentCompany?: string | null
      categoryWork?: string | null
      identificationMethod?: string | null
      /** Format: int32 */
      countCompanyPersonnel?: number | null
    }
    SetInformationDto: {
      education?: string | null
      gender?: components['schemas']['Gender']
      /** Format: date-time */
      brithDate?: string | null
    }
    SetPasswordDto: {
      password?: string | null
    }
    SetSocialNetworkDto: {
      linkdein?: string | null
      twitter?: string | null
      instagram?: string | null
    }
    TerminateSessionByUserInfo: {
      userName?: string | null
      password?: string | null
      sessionIds?: string[] | null
    }
    TerminateSessionsCommandResult: {
      sessionsTerminated?: boolean
    }
    TerminateSessionsCommandResultApiResult: {
      isSuccess?: boolean
      statusCode?: components['schemas']['ApiResultStatusCode']
      message?: string | null
      data?: components['schemas']['TerminateSessionsCommandResult']
    }
    UnFollowByFollowId: {
      /** Format: int64 */
      followId?: number
    }
    UnFollowCompany: {
      /** Format: int64 */
      companyId?: number
    }
    UserSavedGraphSummary: {
      /** Format: int64 */
      id?: number
      name?: string | null
      json?: string | null
      category?: string | null
      /** Format: date-time */
      submitDate?: string
    }
    UserSavedSearchSummary: {
      /** Format: int64 */
      id?: number
      name?: string | null
      url?: string | null
      filters?: string[] | null
      category?: string | null
      /** Format: date-time */
      submitDate?: string
    }
    UserSignInForm: {
      userName: string
      password: string
    }
  }
}

export interface operations {
  SetActivity: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SetActivityDto']
        'application/json': components['schemas']['SetActivityDto']
        'text/json': components['schemas']['SetActivityDto']
        'application/*+json': components['schemas']['SetActivityDto']
      }
    }
  }
  SetInformation: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SetInformationDto']
        'application/json': components['schemas']['SetInformationDto']
        'text/json': components['schemas']['SetInformationDto']
        'application/*+json': components['schemas']['SetInformationDto']
      }
    }
  }
  SetSocialNetwork: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SetSocialNetworkDto']
        'application/json': components['schemas']['SetSocialNetworkDto']
        'text/json': components['schemas']['SetSocialNetworkDto']
        'application/*+json': components['schemas']['SetSocialNetworkDto']
      }
    }
  }
  SetPassword: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['SetPasswordDto']
        'application/json': components['schemas']['SetPasswordDto']
        'text/json': components['schemas']['SetPasswordDto']
        'application/*+json': components['schemas']['SetPasswordDto']
      }
    }
  }
  GetUserProfileByUserId: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['GetUserProfileByUserIdQueryResult']
        }
      }
    }
  }
  GetActiveSessions: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['GetActiveSessionsQueryResultApiResult']
        }
      }
    }
  }
  GetActiveSessionsByUserInfo: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['UserSignInForm']
        'application/json': components['schemas']['UserSignInForm']
        'text/json': components['schemas']['UserSignInForm']
        'application/*+json': components['schemas']['UserSignInForm']
      }
    }
  }
  AddToNewsLetter: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['AddToNewsLetter']
        'application/json': components['schemas']['AddToNewsLetter']
        'text/json': components['schemas']['AddToNewsLetter']
        'application/*+json': components['schemas']['AddToNewsLetter']
      }
    }
  }
  TerminateSessions: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['TerminateSessionsCommandResultApiResult']
        }
      }
    }
    /** شناسه سشن ها */
    requestBody: {
      content: {
        'application/json-patch+json': string[]
        'application/json': string[]
        'text/json': string[]
        'application/*+json': string[]
      }
    }
  }
  TerminateAllSessions: {
    responses: {
      /** Success */
      200: unknown
    }
    requestBody: {
      content: {
        'application/json-patch+json': string[]
        'application/json': string[]
        'text/json': string[]
        'application/*+json': string[]
      }
    }
  }
  TerminateUserSessionByUserInfo: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['ApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['TerminateSessionByUserInfo']
        'application/json': components['schemas']['TerminateSessionByUserInfo']
        'text/json': components['schemas']['TerminateSessionByUserInfo']
        'application/*+json': components['schemas']['TerminateSessionByUserInfo']
      }
    }
  }
  GetSavedGraphList: {
    parameters: {
      query: {
        entityId?: number
      }
    }
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['GetSavedGraphListQueryResultApiResult']
        }
      }
    }
  }
  SaveGraph: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['SaveGraphCommandResultApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['InsertGraphHistoryDto']
        'application/json': components['schemas']['InsertGraphHistoryDto']
        'text/json': components['schemas']['InsertGraphHistoryDto']
        'application/*+json': components['schemas']['InsertGraphHistoryDto']
      }
    }
  }
  GetSavedSearchList: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['GetSavedSearchListQueryResultApiResult']
        }
      }
    }
  }
  SaveSearch: {
    responses: {
      /** Success */
      200: {
        content: {
          'application/json': components['schemas']['SaveSearchCommandResultApiResult']
        }
      }
    }
    requestBody: {
      content: {
        'application/json-patch+json': components['schemas']['InsertAdvancedSearchHistoryDto']
        'application/json': components['schemas']['InsertAdvancedSearchHistoryDto']
        'text/json': components['schemas']['InsertAdvancedSearchHistoryDto']
        'application/*+json': components['schemas']['InsertAdvancedSearchHistoryDto']
      }
    }
  }
}

export interface external {}
