const ROOT = process.env.NEXT_PUBLIC_SERVICES_API
const ANALYTICS_ROOT = process.env.NEXT_PUBLIC_ANALYTICS

export const API = {
  ROOT,
  ANALYTICS_ROOT,
  VISIT_LOG: '/VisitLog',
  UPDATE_VISIT_LOG: '/UpdateVisitLogDuration',
  GET_HOMEPAGE: 'v1/Home/GetHomePage',
  LOGOUT: '/Account/Logout',
  FORGET_PASSWORD: 'v1/Account/ForgetPassword',
  REGISTER: 'v1/Account/SignUp',
  RESET_PASSWORD: 'v1/Account/ResetPassword',
  CONFIRM_OTP: 'v1/Account/ConfirmOTP',
  SIGN_IN: 'v2/Account/SignIn',
  REFRESH_TOKEN: 'v2/Account/RefreshToken',
  SIMPLE_SEARCH: 'v3/Search/Search',
  GET_COMPANY_SUMMARY: 'v2/Companies/GetSummary',
  GET_COMPANY_DETAILS: 'v3/Companies/GetDetails',
  VERIFICATION_SEND_CODE: 'v2/Verification/SendCode',
  VERIFICATION_VERIFY_CODE: 'v2/Verification/VerifyCode',
  LAST_SEEN: 'v1/Profile/EntityPageVisitsAsync',
  GET_PROVINCE: 'v1/Search/GetProvince',
  GET_VAHED_SABTI: 'v1/Search/GetVahedSabti',
  INSERT_REAL_PERSON: 'v1/AfterPay/InsertRealPerson',
  INSERT_LEGAL_PERSON: 'v1/AfterPay/InsertLegalPerson',
  GET_PDF_INVOICE: 'v2/AfterPay/GetPdfInvoice',
  REQUEST_CONSULTANT: 'v1/Crm/RequestConsultant',
  GET_PLANS: 'v3/Pricing',
  GET_PAYMENT_ID: 'v3/Pricing/Pay',
  APPLY_DISCOUNT: 'v3/Pricing/ApplyDiscount',
  GO_TO_IPG: 'v3/Pricing/GotoIPG',
  GET_RECEIPT: 'v3/Pricing/Receipt',
  RE_SEND_OTP_CODE: 'v1/Account/ReSendOtpCode',
  GET_ACTIVE_SESSION: 'v2/Profile/GetActiveSessionsByUserInfo',
  TERMINATE_SESSION: 'v2/Profile/TerminateUserSessionByUserInfo',
  FOLLOW_COMPANY: 'v1/Companies/FollowCompany',
  UNFOLLOW_COMPANY: 'v1/Companies/UnfollowCompany',
  ADD_TO_NEWSLETTER: 'v2/Profile/AddToNewsletter',
  SIGN_IN_BY_OTP: '/Account/SignInByOTP',
}
