export const WEB = {
  ROOT: '/',

  API: '/api-rasmio',
  ABOUT_GRAPH: '/about-graph',
  ABOUT_API: '/about-api',
  ABOUT_ADVANCE_SEARCH: '/about-advanced-search',
  ABOUT_PERSONS: '/about-persons',
  ABOUT_COMPANIES: '/about-companies',
  ABOUT_INDUSTRY: '/about-industry',
  ABOUT_COMPANY_MANAGEMENT: '/company-management',

  ADVANCED_SEARCH_COMPANY: '/advancedSearch/company',
  ADVANCED_SEARCH_PERSON: '/advancedSearch/person',
  ADVANCED_SEARCH_INDUSTRY: '/advancedSearch/industry',
  ADVANCED_SEARCH_PRODUCTS: '/advancedSearch/products',
  ADVANCED_SEARCH_NEWS: '/advancedSearch/news',
  ADVANCED_SEARCH_OWNERSHIP: '/advancedSearch/ownership',
  ADVANCED_SEARCH_LISTS: '/advancedSearch/lists',

  FEATURE_COMPANY: '/about-companies',
  FEATURE_PERSON: '/about-persons',
  FEATURE_INDUSTRY: '/about-industry',
  FEATURE_ADVANCED_SEARCH: '/about-advanced-search',
  FEATURE_CONVENTION: '/rasmio-features/convention',
  FEATURE_GRAPH: '/about-graph',

  FOR_INVESTORS: '/rasmio-for/investors',
  FOR_TRADERS: '/rasmio-for/traders',
  FOR_FINANCIAL_INSTITUTIONS: '/rasmio-for/financialInstitutions',
  FOR_PRODUCERS: '/rasmio-for/producers',
  FOR_MARKETERS: '/rasmio-for/marketers',
  FOR_RESEARCHERS: '/rasmio-for/researchers',
  FOR_GOVERNMENTS: '/rasmio-for/governments',

  ADS: '/about-ads',
  FEED: '/feed',
  DASHBOARD: '/dashboard',
  LIST_MANAGEMENTS: '/list-management',
  CONTACT_US: '/contact',
  ABOUT_US: '/about-us',
  PRICING: '/pricing',
  CHECKOUT: '/checkout',
  FAQ: '/faq',
  TERMS: '/terms',
  PRIVACY: '/terms/#Privacy',
  DISCLAIMER: '/terms/#Disclaimer',
  SOURCES: '/sources',
  PRODUCT: '/product',
  COMPANY_GRAPH: '/companyGraph',
  PERSON_GRAPH: '/personGraph',
  NEWS: '/News/Details/',

  OLD_WEBSITE: 'https://old.rasm.io',
  JOB_OP: 'https://jobinja.ir/companies/rasmio',
  BLOG: 'https://rasm.io/blog',
}
