// url:namatek.com/dashboard/profile
import * as Yup from 'yup'
import { useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import { LoadingButton } from '@mui/lab'
import { Autocomplete, Box, Radio, Stack, TextField, Typography } from '@mui/material'
import FormProvider, { RHFAutocomplete, RHFRadioGroup, RHFTextField } from 'components/hook-form'
import { EcommerceAccountLayout } from '../layout'
import {
  useInfoMutation,
  useSetInfoMutation,
} from 'libs/redux/services/karnama'
import { useEffect, useMemo, useState } from 'react'
import { useSelector } from 'react-redux'
import { RootState } from 'libs/redux/store'
import { useRouter } from 'next/router'
import { notify } from 'utils/notification'
import { useIntl } from 'react-intl'
import { width } from '@mui/system'
import { OptionType } from 'libs/redux/services/karnama'
import dayjs from 'dayjs'
import jalaliday from 'jalaliday'
dayjs.extend(jalaliday);


function EcommerceAccountPersonalView() {
  const [getInfo, { data: dataInfo }] = useInfoMutation()
  const [setInfo, { isLoading }] = useSetInfoMutation()
  const { push } = useRouter()
  const { accessToken } = useSelector((state: RootState) => state.auth)
  const intl = useIntl()
  const [filteredCities, setFilteredCities] = useState<OptionType[]>([])
  const cities = [{ provinceId: "41", label: "کشکسرای" },
  { provinceId: "41", label: "سهند" },
  { provinceId: "41", label: "سیس" },
  { provinceId: "41", label: "دوزدوزان" },
  { provinceId: "41", label: "تیمورلو" },
  { provinceId: "41", label: "صوفیان" },
  { provinceId: "41", label: "سردرود" },
  { provinceId: "41", label: "هادیشهر" },
  { provinceId: "41", label: "هشترود" },
  { provinceId: "41", label: "زرنق" },
  { provinceId: "41", label: "ترکمانچای" },
  { provinceId: "41", label: "ورزقان" },
  { provinceId: "41", label: "تسوج" },
  { provinceId: "41", label: "زنوز" },
  { provinceId: "41", label: "ایلخچی" },
  { provinceId: "41", label: "شرفخانه" },
  { provinceId: "41", label: "مهربان" },
  { provinceId: "41", label: "مبارک شهر" },
  { provinceId: "41", label: "تیکمه داش" },
  { provinceId: "41", label: "باسمنج" },
  { provinceId: "41", label: "سیه رود" },
  { provinceId: "41", label: "میانه" },
  { provinceId: "41", label: "خمارلو" },
  { provinceId: "41", label: "خواجه" },
  { provinceId: "41", label: "بناب مرند" },
  { provinceId: "41", label: "قره آغاج" },
  { provinceId: "41", label: "وایقان" },
  { provinceId: "41", label: "مراغه" },
  { provinceId: "41", label: "ممقان" },
  { provinceId: "41", label: "خامنه" },
  { provinceId: "41", label: "خسروشاه" },
  { provinceId: "41", label: "لیلان" },
  { provinceId: "41", label: "نظرکهریزی" },
  { provinceId: "41", label: "اهر" },
  { provinceId: "41", label: "بخشایش" },
  { provinceId: "41", label: "آقکند" },
  { provinceId: "41", label: "جوان قلعه" },
  { provinceId: "41", label: "کلیبر" },
  { provinceId: "41", label: "مرند" },
  { provinceId: "41", label: "اسکو" },
  { provinceId: "41", label: "شندآباد" },
  { provinceId: "41", label: "شربیان" },
  { provinceId: "41", label: "گوگان" },
  { provinceId: "41", label: "بستان آباد" },
  { provinceId: "41", label: "تبریز" },
  { provinceId: "41", label: "جلفا" },
  { provinceId: "41", label: "اچاچی" },
  { provinceId: "41", label: "هریس" },
  { provinceId: "41", label: "یامچی" },
  { provinceId: "41", label: "خاروانا" },
  { provinceId: "41", label: "کوزه کنان" },
  { provinceId: "41", label: "خداجو(خراجو)" },
  { provinceId: "41", label: "آذرشهر" },
  { provinceId: "41", label: "شبستر" },
  { provinceId: "41", label: "سراب" },
  { provinceId: "41", label: "ملکان" },
  { provinceId: "41", label: "بناب" },
  { provinceId: "41", label: "هوراند" },
  { provinceId: "41", label: "کلوانق" },
  { provinceId: "41", label: "ترک" },
  { provinceId: "41", label: "عجب شیر" },
  { provinceId: "41", label: "آبش احمد" },
  { provinceId: "44", label: "تازه شهر" },
  { provinceId: "44", label: "نالوس" },
  { provinceId: "44", label: "ایواوغلی" },
  { provinceId: "44", label: "شاهین دژ" },
  { provinceId: "44", label: "گردکشانه" },
  { provinceId: "44", label: "باروق" },
  { provinceId: "44", label: "سیلوانه" },
  { provinceId: "44", label: "بازرگان" },
  { provinceId: "44", label: "نازک علیا" },
  { provinceId: "44", label: "ربط" },
  { provinceId: "44", label: "تکاب" },
  { provinceId: "44", label: "دیزج دیز" },
  { provinceId: "44", label: "سیمینه" },
  { provinceId: "44", label: "نوشین" },
  { provinceId: "44", label: "میاندوآب" },
  { provinceId: "44", label: "مرگنلر" },
  { provinceId: "44", label: "سلماس" },
  { provinceId: "44", label: "آواجیق" },
  { provinceId: "44", label: "قطور" },
  { provinceId: "44", label: "محمودآباد" },
  { provinceId: "44", label: "خوی" },
  { provinceId: "44", label: "نقده" },
  { provinceId: "44", label: "سرو" },
  { provinceId: "44", label: "خلیفان" },
  { provinceId: "44", label: "پلدشت" },
  { provinceId: "44", label: "میرآباد" },
  { provinceId: "44", label: "اشنویه" },
  { provinceId: "44", label: "زرآباد" },
  { provinceId: "44", label: "بوکان" },
  { provinceId: "44", label: "پیرانشهر" },
  { provinceId: "44", label: "چهاربرج" },
  { provinceId: "44", label: "قوشچی" },
  { provinceId: "44", label: "شوط" },
  { provinceId: "44", label: "ماکو" },
  { provinceId: "44", label: "سیه چشمه" },
  { provinceId: "44", label: "سردشت" },
  { provinceId: "44", label: "کشاورز" },
  { provinceId: "44", label: "فیرورق" },
  { provinceId: "44", label: "محمدیار" },
  { provinceId: "44", label: "ارومیه" },
  { provinceId: "44", label: "مهاباد" },
  { provinceId: "44", label: "قره ضیاءالدین" },
  { provinceId: "45", label: "پارس آباد" },
  { provinceId: "45", label: "فخراباد" },
  { provinceId: "45", label: "کلور" },
  { provinceId: "45", label: "نیر" },
  { provinceId: "45", label: "اردبیل" },
  { provinceId: "45", label: "اسلام اباد" },
  { provinceId: "45", label: "تازه کندانگوت" },
  { provinceId: "45", label: "مشگین شهر" },
  { provinceId: "45", label: "جعفرآباد" },
  { provinceId: "45", label: "نمین" },
  { provinceId: "45", label: "اصلاندوز" },
  { provinceId: "45", label: "مرادلو" },
  { provinceId: "45", label: "خلخال" },
  { provinceId: "45", label: "کوراییم" },
  { provinceId: "45", label: "هیر" },
  { provinceId: "45", label: "گیوی" },
  { provinceId: "45", label: "گرمی" },
  { provinceId: "45", label: "لاهرود" },
  { provinceId: "45", label: "هشتجین" },
  { provinceId: "45", label: "عنبران" },
  { provinceId: "45", label: "تازه کند" },
  { provinceId: "45", label: "قصابه" },
  { provinceId: "45", label: "رضی" },
  { provinceId: "45", label: "سرعین" },
  { provinceId: "45", label: "بیله سوار" },
  { provinceId: "45", label: "آبی بیگلو" },
  { provinceId: "31", label: "گزبرخوار" },
  { provinceId: "31", label: "زیار" },
  { provinceId: "31", label: "زرین شهر" },
  { provinceId: "31", label: "گلشن" },
  { provinceId: "31", label: "پیربکران" },
  { provinceId: "31", label: "خالدآباد" },
  { provinceId: "31", label: "سجزی" },
  { provinceId: "31", label: "گوگد" },
  { provinceId: "31", label: "تیران" },
  { provinceId: "31", label: "ونک" },
  { provinceId: "31", label: "دهق" },
  { provinceId: "31", label: "زواره" },
  { provinceId: "31", label: "کاشان" },
  { provinceId: "31", label: "ابوزیدآباد" },
  { provinceId: "31", label: "اصغرآباد" },
  { provinceId: "31", label: "بافران" },
  { provinceId: "31", label: "شهرضا" },
  { provinceId: "31", label: "خور" },
  { provinceId: "31", label: "مجلسی" },
  { provinceId: "31", label: "هرند" },
  { provinceId: "31", label: "فولادشهر" },
  { provinceId: "31", label: "کمشچه" },
  { provinceId: "31", label: "کلیشادوسودرجان" },
  { provinceId: "31", label: "لای بید" },
  { provinceId: "31", label: "قهجاورستان" },
  { provinceId: "31", label: "چرمهین" },
  { provinceId: "31", label: "رزوه" },
  { provinceId: "31", label: "فریدونشهر" },
  { provinceId: "31", label: "طرق رود" },
  { provinceId: "31", label: "نصرآباد" },
  { provinceId: "31", label: "برزک" },
  { provinceId: "31", label: "سفیدشهر" },
  { provinceId: "31", label: "سمیرم" },
  { provinceId: "31", label: "گلدشت" },
  { provinceId: "31", label: "اردستان" },
  { provinceId: "31", label: "جوشقان قالی" },
  { provinceId: "31", label: "بویین ومیاندشت" },
  { provinceId: "31", label: "کرکوند" },
  { provinceId: "31", label: "درچه" },
  { provinceId: "31", label: "انارک" },
  { provinceId: "31", label: "دولت آباد" },
  { provinceId: "31", label: "ایمانشهر" },
  { provinceId: "31", label: "گرگاب" },
  { provinceId: "31", label: "حسن اباد" },
  { provinceId: "31", label: "سده لنجان" },
  { provinceId: "31", label: "حبیب آباد" },
  { provinceId: "31", label: "بهاران شهر" },
  { provinceId: "31", label: "میمه" },
  { provinceId: "31", label: "تودشک" },
  { provinceId: "31", label: "گلشهر" },
  { provinceId: "31", label: "رضوانشهر" },
  { provinceId: "31", label: "داران" },
  { provinceId: "31", label: "علویجه" },
  { provinceId: "31", label: "نیک آباد" },
  { provinceId: "31", label: "مشکات" },
  { provinceId: "31", label: "آران وبیدگل" },
  { provinceId: "31", label: "خوانسار" },
  { provinceId: "31", label: "نجف آباد" },
  { provinceId: "31", label: "منظریه" },
  { provinceId: "31", label: "فرخی" },
  { provinceId: "31", label: "دیزیچه" },
  { provinceId: "31", label: "اژیه" },
  { provinceId: "31", label: "زاینده رود" },
  { provinceId: "31", label: "خورزوق" },
  { provinceId: "31", label: "قهدریجان" },
  { provinceId: "31", label: "شاهین شهر" },
  { provinceId: "31", label: "بهارستان" },
  { provinceId: "31", label: "چمگردان" },
  { provinceId: "31", label: "دهاقان" },
  { provinceId: "31", label: "برف انبار" },
  { provinceId: "31", label: "بادرود" },
  { provinceId: "31", label: "کوهپایه" },
  { provinceId: "31", label: "گلپایگان" },
  { provinceId: "31", label: "عسگران" },
  { provinceId: "31", label: "حنا" },
  { provinceId: "31", label: "کهریزسنگ" },
  { provinceId: "31", label: "مهاباد" },
  { provinceId: "31", label: "کامو و چوگان" },
  { provinceId: "31", label: "افوس" },
  { provinceId: "31", label: "زیباشهر" },
  { provinceId: "31", label: "کوشک" },
  { provinceId: "31", label: "نایین" },
  { provinceId: "31", label: "سین" },
  { provinceId: "31", label: "زازران" },
  { provinceId: "31", label: "مبارکه" },
  { provinceId: "31", label: "ورزنه" },
  { provinceId: "31", label: "ورنامخواست" },
  { provinceId: "31", label: "شاپورآباد" },
  { provinceId: "31", label: "فلاورجان" },
  { provinceId: "31", label: "وزوان" },
  { provinceId: "31", label: "اصفهان" },
  { provinceId: "31", label: "باغ بهادران" },
  { provinceId: "31", label: "چادگان" },
  { provinceId: "31", label: "دامنه" },
  { provinceId: "31", label: "نطنز" },
  { provinceId: "31", label: "محمدآباد" },
  { provinceId: "31", label: "نیاسر" },
  { provinceId: "31", label: "نوش آباد" },
  { provinceId: "31", label: "کمه" },
  { provinceId: "31", label: "جوزدان" },
  { provinceId: "31", label: "قمصر" },
  { provinceId: "31", label: "جندق" },
  { provinceId: "31", label: "طالخونچه" },
  { provinceId: "31", label: "خمینی شهر" },
  { provinceId: "31", label: "باغشاد" },
  { provinceId: "31", label: "دستگرد" },
  { provinceId: "31", label: "ابریشم" },
  { provinceId: "26", label: "چهارباغ" },
  { provinceId: "26", label: "آسارا" },
  { provinceId: "26", label: "کرج" },
  { provinceId: "26", label: "طالقان" },
  { provinceId: "26", label: "شهرجدیدهشتگرد" },
  { provinceId: "26", label: "محمدشهر" },
  { provinceId: "26", label: "مشکین دشت" },
  { provinceId: "26", label: "نظرآباد" },
  { provinceId: "26", label: "هشتگرد" },
  { provinceId: "26", label: "ماهدشت" },
  { provinceId: "26", label: "اشتهارد" },
  { provinceId: "26", label: "کوهسار" },
  { provinceId: "26", label: "گرمدره" },
  { provinceId: "26", label: "تنکمان" },
  { provinceId: "26", label: "گلسار" },
  { provinceId: "26", label: "کمال شهر" },
  { provinceId: "26", label: "فردیس" },
  { provinceId: "84", label: "آبدانان" },
  { provinceId: "84", label: "شباب" },
  { provinceId: "84", label: "موسیان" },
  { provinceId: "84", label: "بدره" },
  { provinceId: "84", label: "ایلام" },
  { provinceId: "84", label: "ایوان" },
  { provinceId: "84", label: "مهران" },
  { provinceId: "84", label: "آسمان آباد" },
  { provinceId: "84", label: "پهله" },
  { provinceId: "84", label: "مهر" },
  { provinceId: "84", label: "سراب باغ" },
  { provinceId: "84", label: "بلاوه" },
  { provinceId: "84", label: "میمه" },
  { provinceId: "84", label: "دره شهر" },
  { provinceId: "84", label: "ارکواز" },
  { provinceId: "84", label: "مورموری" },
  { provinceId: "84", label: "توحید" },
  { provinceId: "84", label: "دهلران" },
  { provinceId: "84", label: "لومار" },
  { provinceId: "84", label: "چوار" },
  { provinceId: "84", label: "زرنه" },
  { provinceId: "84", label: "صالح آباد" },
  { provinceId: "84", label: "سرابله" },
  { provinceId: "84", label: "ماژین" },
  { provinceId: "84", label: "دلگشا" },
  { provinceId: "77", label: "ریز" },
  { provinceId: "77", label: "برازجان" },
  { provinceId: "77", label: "بندرریگ" },
  { provinceId: "77", label: "اهرم" },
  { provinceId: "77", label: "دوراهک" },
  { provinceId: "77", label: "خورموج" },
  { provinceId: "77", label: "نخل تقی" },
  { provinceId: "77", label: "کلمه" },
  { provinceId: "77", label: "بندردیلم" },
  { provinceId: "77", label: "وحدتیه" },
  { provinceId: "77", label: "بنک" },
  { provinceId: "77", label: "چغادک" },
  { provinceId: "77", label: "بندردیر" },
  { provinceId: "77", label: "کاکی" },
  { provinceId: "77", label: "جم" },
  { provinceId: "77", label: "دالکی" },
  { provinceId: "77", label: "بندرگناوه" },
  { provinceId: "77", label: "آباد" },
  { provinceId: "77", label: "آبدان" },
  { provinceId: "77", label: "خارک" },
  { provinceId: "77", label: "شنبه" },
  { provinceId: "77", label: "بوشکان" },
  { provinceId: "77", label: "انارستان" },
  { provinceId: "77", label: "شبانکاره" },
  { provinceId: "77", label: "سیراف" },
  { provinceId: "77", label: "دلوار" },
  { provinceId: "77", label: "بردستان" },
  { provinceId: "77", label: "بادوله" },
  { provinceId: "77", label: "عسلویه" },
  { provinceId: "77", label: "تنگ ارم" },
  { provinceId: "77", label: "امام حسن" },
  { provinceId: "77", label: "سعد آباد" },
  { provinceId: "77", label: "بندرکنگان" },
  { provinceId: "77", label: "بوشهر" },
  { provinceId: "77", label: "بردخون" },
  { provinceId: "77", label: "آب پخش" },
  { provinceId: "21", label: "شاهدشهر" },
  { provinceId: "21", label: "پیشوا" },
  { provinceId: "21", label: "جوادآباد" },
  { provinceId: "21", label: "ارجمند" },
  { provinceId: "21", label: "ری" },
  { provinceId: "21", label: "نصیرشهر" },
  { provinceId: "21", label: "رودهن" },
  { provinceId: "21", label: "اندیشه" },
  { provinceId: "21", label: "نسیم شهر" },
  { provinceId: "21", label: "صباشهر" },
  { provinceId: "21", label: "ملارد" },
  { provinceId: "21", label: "شمشک" },
  { provinceId: "21", label: "پاکدشت" },
  { provinceId: "21", label: "باقرشهر" },
  { provinceId: "21", label: "احمد آباد مستوفی" },
  { provinceId: "21", label: "کیلان" },
  { provinceId: "21", label: "قرچک" },
  { provinceId: "21", label: "فردوسیه" },
  { provinceId: "21", label: "گلستان" },
  { provinceId: "21", label: "ورامین" },
  { provinceId: "21", label: "فیروزکوه" },
  { provinceId: "21", label: "فشم" },
  { provinceId: "21", label: "پرند" },
  { provinceId: "21", label: "آبعلی" },
  { provinceId: "21", label: "چهاردانگه" },
  { provinceId: "21", label: "تهران" },
  { provinceId: "21", label: "بومهن" },
  { provinceId: "21", label: "وحیدیه" },
  { provinceId: "21", label: "صفادشت" },
  { provinceId: "21", label: "لواسان" },
  { provinceId: "21", label: "فرون اباد" },
  { provinceId: "21", label: "کهریزک" },
  { provinceId: "21", label: "رباطکریم" },
  { provinceId: "21", label: "آبسرد" },
  { provinceId: "21", label: "باغستان" },
  { provinceId: "21", label: "صالحیه" },
  { provinceId: "21", label: "شهریار" },
  { provinceId: "21", label: "قدس" },
  { provinceId: "21", label: "تجریش" },
  { provinceId: "21", label: "شریف آباد" },
  { provinceId: "21", label: "حسن آباد" },
  { provinceId: "21", label: "اسلامشهر" },
  { provinceId: "21", label: "دماوند" },
  { provinceId: "21", label: "پردیس" },
  { provinceId: "38", label: "وردنجان" },
  { provinceId: "38", label: "گوجان" },
  { provinceId: "38", label: "گهرو" },
  { provinceId: "38", label: "سورشجان" },
  { provinceId: "38", label: "سرخون" },
  { provinceId: "38", label: "شهرکرد" },
  { provinceId: "38", label: "منج" },
  { provinceId: "38", label: "بروجن" },
  { provinceId: "38", label: "پردنجان" },
  { provinceId: "38", label: "سامان" },
  { provinceId: "38", label: "فرخ شهر" },
  { provinceId: "38", label: "صمصامی" },
  { provinceId: "38", label: "طاقانک" },
  { provinceId: "38", label: "کاج" },
  { provinceId: "38", label: "نقنه" },
  { provinceId: "38", label: "لردگان" },
  { provinceId: "38", label: "باباحیدر" },
  { provinceId: "38", label: "دستنا" },
  { provinceId: "38", label: "سودجان" },
  { provinceId: "38", label: "بازفت" },
  { provinceId: "38", label: "هفشجان" },
  { provinceId: "38", label: "سردشت" },
  { provinceId: "38", label: "فرادبنه" },
  { provinceId: "38", label: "چلیچه" },
  { provinceId: "38", label: "بن" },
  { provinceId: "38", label: "فارسان" },
  { provinceId: "38", label: "شلمزار" },
  { provinceId: "38", label: "نافچ" },
  { provinceId: "38", label: "دشتک" },
  { provinceId: "38", label: "بلداجی" },
  { provinceId: "38", label: "آلونی" },
  { provinceId: "38", label: "گندمان" },
  { provinceId: "38", label: "جونقان" },
  { provinceId: "38", label: "ناغان" },
  { provinceId: "38", label: "هارونی" },
  { provinceId: "38", label: "چلگرد" },
  { provinceId: "38", label: "کیان" },
  { provinceId: "38", label: "اردل" },
  { provinceId: "38", label: "سفیددشت" },
  { provinceId: "38", label: "مال خلیفه" },
  { provinceId: "56", label: "اسلامیه" },
  { provinceId: "56", label: "شوسف" },
  { provinceId: "56", label: "قاین" },
  { provinceId: "56", label: "عشق آباد" },
  { provinceId: "56", label: "طبس مسینا" },
  { provinceId: "56", label: "ارسک" },
  { provinceId: "56", label: "آیسک" },
  { provinceId: "56", label: "نیمبلوک" },
  { provinceId: "56", label: "دیهوک" },
  { provinceId: "56", label: "سربیشه" },
  { provinceId: "56", label: "محمدشهر" },
  { provinceId: "56", label: "بیرجند" },
  { provinceId: "56", label: "فردوس" },
  { provinceId: "56", label: "نهبندان" },
  { provinceId: "56", label: "اسفدن" },
  { provinceId: "56", label: "گزیک" },
  { provinceId: "56", label: "حاجی آباد" },
  { provinceId: "56", label: "سه قلعه" },
  { provinceId: "56", label: "آرین شهر" },
  { provinceId: "56", label: "مود" },
  { provinceId: "56", label: "خوسف" },
  { provinceId: "56", label: "قهستان" },
  { provinceId: "56", label: "بشرویه" },
  { provinceId: "56", label: "سرایان" },
  { provinceId: "56", label: "خضری دشت بیاض" },
  { provinceId: "56", label: "طبس" },
  { provinceId: "56", label: "اسدیه" },
  { provinceId: "56", label: "زهان" },
  { provinceId: "51", label: "بار" },
  { provinceId: "51", label: "نیل شهر" },
  { provinceId: "51", label: "جنگل" },
  { provinceId: "51", label: "درود" },
  { provinceId: "51", label: "رباط سنگ" },
  { provinceId: "51", label: "سلطان آباد" },
  { provinceId: "51", label: "فریمان" },
  { provinceId: "51", label: "گناباد" },
  { provinceId: "51", label: "کاریز" },
  { provinceId: "51", label: "همت آباد" },
  { provinceId: "51", label: "سلامی" },
  { provinceId: "51", label: "باجگیران" },
  { provinceId: "51", label: "بجستان" },
  { provinceId: "51", label: "چناران" },
  { provinceId: "51", label: "درگز" },
  { provinceId: "51", label: "کلات" },
  { provinceId: "51", label: "چکنه" },
  { provinceId: "51", label: "نصرآباد" },
  { provinceId: "51", label: "بردسکن" },
  { provinceId: "51", label: "مشهد" },
  { provinceId: "51", label: "کدکن" },
  { provinceId: "51", label: "نقاب" },
  { provinceId: "51", label: "قلندرآباد" },
  { provinceId: "51", label: "کاشمر" },
  { provinceId: "51", label: "شاندیز" },
  { provinceId: "51", label: "نشتیفان" },
  { provinceId: "51", label: "ششتمد" },
  { provinceId: "51", label: "شادمهر" },
  { provinceId: "51", label: "عشق آباد" },
  { provinceId: "51", label: "چاپشلو" },
  { provinceId: "51", label: "رشتخوار" },
  { provinceId: "51", label: "قدمگاه" },
  { provinceId: "51", label: "صالح آباد" },
  { provinceId: "51", label: "داورزن" },
  { provinceId: "51", label: "فرهادگرد" },
  { provinceId: "51", label: "کاخک" },
  { provinceId: "51", label: "مشهدریزه" },
  { provinceId: "51", label: "جغتای" },
  { provinceId: "51", label: "مزدآوند" },
  { provinceId: "51", label: "قوچان" },
  { provinceId: "51", label: "یونسی" },
  { provinceId: "51", label: "سنگان" },
  { provinceId: "51", label: "نوخندان" },
  { provinceId: "51", label: "کندر" },
  { provinceId: "51", label: "نیشابور" },
  { provinceId: "51", label: "احمدابادصولت" },
  { provinceId: "51", label: "شهراباد" },
  { provinceId: "51", label: "رضویه" },
  { provinceId: "51", label: "تربت حیدریه" },
  { provinceId: "51", label: "باخرز" },
  { provinceId: "51", label: "سفیدسنگ" },
  { provinceId: "51", label: "بیدخت" },
  { provinceId: "51", label: "تایباد" },
  { provinceId: "51", label: "فیروزه" },
  { provinceId: "51", label: "قاسم آباد" },
  { provinceId: "51", label: "سبزوار" },
  { provinceId: "51", label: "فیض آباد" },
  { provinceId: "51", label: "گلمکان" },
  { provinceId: "51", label: "لطف آباد" },
  { provinceId: "51", label: "شهرزو" },
  { provinceId: "51", label: "خرو" },
  { provinceId: "51", label: "تربت جام" },
  { provinceId: "51", label: "انابد" },
  { provinceId: "51", label: "ملک آباد" },
  { provinceId: "51", label: "بایک" },
  { provinceId: "51", label: "دولت آباد" },
  { provinceId: "51", label: "سرخس" },
  { provinceId: "51", label: "ریوش" },
  { provinceId: "51", label: "طرقبه" },
  { provinceId: "51", label: "خواف" },
  { provinceId: "51", label: "روداب" },
  { provinceId: "51", label: "خلیل آباد" },
  { provinceId: "58", label: "چناران شهر" },
  { provinceId: "58", label: "راز" },
  { provinceId: "58", label: "پیش قلعه" },
  { provinceId: "58", label: "قوشخانه" },
  { provinceId: "58", label: "شوقان" },
  { provinceId: "58", label: "اسفراین" },
  { provinceId: "58", label: "گرمه" },
  { provinceId: "58", label: "قاضی" },
  { provinceId: "58", label: "شیروان" },
  { provinceId: "58", label: "حصارگرمخان" },
  { provinceId: "58", label: "آشخانه" },
  { provinceId: "58", label: "تیتکانلو" },
  { provinceId: "58", label: "جاجرم" },
  { provinceId: "58", label: "بجنورد" },
  { provinceId: "58", label: "درق" },
  { provinceId: "58", label: "آوا" },
  { provinceId: "58", label: "زیارت" },
  { provinceId: "58", label: "سنخواست" },
  { provinceId: "58", label: "صفی آباد" },
  { provinceId: "58", label: "ایور" },
  { provinceId: "58", label: "فاروج" },
  { provinceId: "58", label: "لوجلی" },
  { provinceId: "61", label: "هفتگل" },
  { provinceId: "61", label: "بیدروبه" },
  { provinceId: "61", label: "شاوور" },
  { provinceId: "61", label: "حمزه" },
  { provinceId: "61", label: "گتوند" },
  { provinceId: "61", label: "شرافت" },
  { provinceId: "61", label: "منصوریه" },
  { provinceId: "61", label: "زهره" },
  { provinceId: "61", label: "رامهرمز" },
  { provinceId: "61", label: "بندرامام خمینی" },
  { provinceId: "61", label: "کوت عبداله" },
  { provinceId: "61", label: "میداود" },
  { provinceId: "61", label: "چغامیش" },
  { provinceId: "61", label: "ملاثانی" },
  { provinceId: "61", label: "چم گلک" },
  { provinceId: "61", label: "حر" },
  { provinceId: "61", label: "شمس آباد" },
  { provinceId: "61", label: "آبژدان" },
  { provinceId: "61", label: "چویبده" },
  { provinceId: "61", label: "مسجدسلیمان" },
  { provinceId: "61", label: "مقاومت" },
  { provinceId: "61", label: "ترکالکی" },
  { provinceId: "61", label: "دارخوین" },
  { provinceId: "61", label: "سردشت" },
  { provinceId: "61", label: "لالی" },
  { provinceId: "61", label: "کوت سیدنعیم" },
  { provinceId: "61", label: "حمیدیه" },
  { provinceId: "61", label: "دهدز" },
  { provinceId: "61", label: "قلعه تل" },
  { provinceId: "61", label: "میانرود" },
  { provinceId: "61", label: "رفیع" },
  { provinceId: "61", label: "اندیمشک" },
  { provinceId: "61", label: "الوان" },
  { provinceId: "61", label: "سالند" },
  { provinceId: "61", label: "صالح شهر" },
  { provinceId: "61", label: "اروندکنار" },
  { provinceId: "61", label: "سرداران" },
  { provinceId: "61", label: "تشان" },
  { provinceId: "61", label: "رامشیر" },
  { provinceId: "61", label: "شادگان" },
  { provinceId: "61", label: "بندرماهشهر" },
  { provinceId: "61", label: "جایزان" },
  { provinceId: "61", label: "بستان" },
  { provinceId: "61", label: "ویس" },
  { provinceId: "61", label: "اهواز" },
  { provinceId: "61", label: "فتح المبین" },
  { provinceId: "61", label: "شهر امام" },
  { provinceId: "61", label: "قلعه خواجه" },
  { provinceId: "61", label: "حسینیه" },
  { provinceId: "61", label: "گلگیر" },
  { provinceId: "61", label: "مینوشهر" },
  { provinceId: "61", label: "سماله" },
  { provinceId: "61", label: "شوشتر" },
  { provinceId: "61", label: "بهبهان" },
  { provinceId: "61", label: "هندیجان" },
  { provinceId: "61", label: "ابوحمیظه" },
  { provinceId: "61", label: "آغاجاری" },
  { provinceId: "61", label: "ایذه" },
  { provinceId: "61", label: "صیدون" },
  { provinceId: "61", label: "سیاه منصور" },
  { provinceId: "61", label: "هویزه" },
  { provinceId: "61", label: "آزادی" },
  { provinceId: "61", label: "شوش" },
  { provinceId: "61", label: "دزفول" },
  { provinceId: "61", label: "جنت مکان" },
  { provinceId: "61", label: "آبادان" },
  { provinceId: "61", label: "گوریه" },
  { provinceId: "61", label: "خرمشهر" },
  { provinceId: "61", label: "مشراگه" },
  { provinceId: "61", label: "خنافره" },
  { provinceId: "61", label: "چمران" },
  { provinceId: "61", label: "امیدیه" },
  { provinceId: "61", label: "سوسنگرد" },
  { provinceId: "61", label: "شیبان" },
  { provinceId: "61", label: "الهایی" },
  { provinceId: "61", label: "باغ ملک" },
  { provinceId: "61", label: "صفی آباد" },
  { provinceId: "24", label: "سجاس" },
  { provinceId: "24", label: "زرین رود" },
  { provinceId: "24", label: "آب بر" },
  { provinceId: "24", label: "ارمغانخانه" },
  { provinceId: "24", label: "کرسف" },
  { provinceId: "24", label: "هیدج" },
  { provinceId: "24", label: "سلطانیه" },
  { provinceId: "24", label: "خرمدره" },
  { provinceId: "24", label: "نیک پی" },
  { provinceId: "24", label: "قیدار" },
  { provinceId: "24", label: "ابهر" },
  { provinceId: "24", label: "دندی" },
  { provinceId: "24", label: "حلب" },
  { provinceId: "24", label: "نوربهار" },
  { provinceId: "24", label: "گرماب" },
  { provinceId: "24", label: "چورزق" },
  { provinceId: "24", label: "زنجان" },
  { provinceId: "24", label: "سهرورد" },
  { provinceId: "24", label: "صایین قلعه" },
  { provinceId: "24", label: "ماه نشان" },
  { provinceId: "24", label: "زرین آباد" },
  { provinceId: "23", label: "ایوانکی" },
  { provinceId: "23", label: "مجن" },
  { provinceId: "23", label: "دامغان" },
  { provinceId: "23", label: "سرخه" },
  { provinceId: "23", label: "مهدی شهر" },
  { provinceId: "23", label: "شاهرود" },
  { provinceId: "23", label: "سمنان" },
  { provinceId: "23", label: "کهن آباد" },
  { provinceId: "23", label: "گرمسار" },
  { provinceId: "23", label: "کلاته خیج" },
  { provinceId: "23", label: "دیباج" },
  { provinceId: "23", label: "درجزین" },
  { provinceId: "23", label: "رودیان" },
  { provinceId: "23", label: "بسطام" },
  { provinceId: "23", label: "امیریه" },
  { provinceId: "23", label: "میامی" },
  { provinceId: "23", label: "شهمیرزاد" },
  { provinceId: "23", label: "بیارجمند" },
  { provinceId: "23", label: "کلاته" },
  { provinceId: "23", label: "آرادان" },
  { provinceId: "54", label: "محمدی" },
  { provinceId: "54", label: "شهرک علی اکبر" },
  { provinceId: "54", label: "بنجار" },
  { provinceId: "54", label: "گلمورتی" },
  { provinceId: "54", label: "نگور" },
  { provinceId: "54", label: "راسک" },
  { provinceId: "54", label: "بنت" },
  { provinceId: "54", label: "قصرقند" },
  { provinceId: "54", label: "جالق" },
  { provinceId: "54", label: "هیدوچ" },
  { provinceId: "54", label: "نوک آباد" },
  { provinceId: "54", label: "زهک" },
  { provinceId: "54", label: "بمپور" },
  { provinceId: "54", label: "پیشین" },
  { provinceId: "54", label: "گشت" },
  { provinceId: "54", label: "محمدآباد" },
  { provinceId: "54", label: "زاهدان" },
  { provinceId: "54", label: "زابلی" },
  { provinceId: "54", label: "چاه بهار" },
  { provinceId: "54", label: "زرآباد" },
  { provinceId: "54", label: "بزمان" },
  { provinceId: "54", label: "اسپکه" },
  { provinceId: "54", label: "فنوج" },
  { provinceId: "54", label: "سراوان" },
  { provinceId: "54", label: "ادیمی" },
  { provinceId: "54", label: "زابل" },
  { provinceId: "54", label: "دوست محمد" },
  { provinceId: "54", label: "ایرانشهر" },
  { provinceId: "54", label: "سرباز" },
  { provinceId: "54", label: "سیرکان" },
  { provinceId: "54", label: "میرجاوه" },
  { provinceId: "54", label: "نصرت آباد" },
  { provinceId: "54", label: "سوران" },
  { provinceId: "54", label: "خاش" },
  { provinceId: "54", label: "کنارک" },
  { provinceId: "54", label: "محمدان" },
  { provinceId: "54", label: "نیک شهر" },
  { provinceId: "71", label: "کازرون" },
  { provinceId: "71", label: "کارزین (فتح آباد)" },
  { provinceId: "71", label: "فدامی" },
  { provinceId: "71", label: "خومه زار" },
  { provinceId: "71", label: "سلطان شهر" },
  { provinceId: "71", label: "فیروزآباد" },
  { provinceId: "71", label: "دبیران" },
  { provinceId: "71", label: "باب انار" },
  { provinceId: "71", label: "رامجرد" },
  { provinceId: "71", label: "سروستان" },
  { provinceId: "71", label: "قره بلاغ" },
  { provinceId: "71", label: "ارسنجان" },
  { provinceId: "71", label: "دژکرد" },
  { provinceId: "71", label: "بیرم" },
  { provinceId: "71", label: "دهرم" },
  { provinceId: "71", label: "شیراز" },
  { provinceId: "71", label: "ایزدخواست" },
  { provinceId: "71", label: "علامرودشت" },
  { provinceId: "71", label: "اوز" },
  { provinceId: "71", label: "وراوی" },
  { provinceId: "71", label: "بیضا" },
  { provinceId: "71", label: "نی ریز" },
  { provinceId: "71", label: "کنارتخته" },
  { provinceId: "71", label: "امام شهر" },
  { provinceId: "71", label: "جهرم" },
  { provinceId: "71", label: "بابامنیر" },
  { provinceId: "71", label: "گراش" },
  { provinceId: "71", label: "فسا" },
  { provinceId: "71", label: "شهرپیر" },
  { provinceId: "71", label: "حسن اباد" },
  { provinceId: "71", label: "کامفیروز" },
  { provinceId: "71", label: "خنج" },
  { provinceId: "71", label: "خانه زنیان" },
  { provinceId: "71", label: "استهبان" },
  { provinceId: "71", label: "بوانات" },
  { provinceId: "71", label: "لطیفی" },
  { provinceId: "71", label: "فراشبند" },
  { provinceId: "71", label: "زرقان" },
  { provinceId: "71", label: "صغاد" },
  { provinceId: "71", label: "اشکنان" },
  { provinceId: "71", label: "قایمیه" },
  { provinceId: "71", label: "گله دار" },
  { provinceId: "71", label: "دوبرجی" },
  { provinceId: "71", label: "آباده طشک" },
  { provinceId: "71", label: "خرامه" },
  { provinceId: "71", label: "میمند" },
  { provinceId: "71", label: "افزر" },
  { provinceId: "71", label: "دوزه" },
  { provinceId: "71", label: "سیدان" },
  { provinceId: "71", label: "کوپن" },
  { provinceId: "71", label: "زاهدشهر" },
  { provinceId: "71", label: "قادراباد" },
  { provinceId: "71", label: "سده" },
  { provinceId: "71", label: "بنارویه" },
  { provinceId: "71", label: "سعادت شهر" },
  { provinceId: "71", label: "شهرصدرا" },
  { provinceId: "71", label: "سورمق" },
  { provinceId: "71", label: "حسامی" },
  { provinceId: "71", label: "جویم" },
  { provinceId: "71", label: "خوزی" },
  { provinceId: "71", label: "اردکان" },
  { provinceId: "71", label: "قطرویه" },
  { provinceId: "71", label: "نودان" },
  { provinceId: "71", label: "مبارک آباددیز" },
  { provinceId: "71", label: "داراب" },
  { provinceId: "71", label: "نورآباد" },
  { provinceId: "71", label: "کوار" },
  { provinceId: "71", label: "نوبندگان" },
  { provinceId: "71", label: "حاجی آباد" },
  { provinceId: "71", label: "خاوران" },
  { provinceId: "71", label: "مرودشت" },
  { provinceId: "71", label: "کوهنجان" },
  { provinceId: "71", label: "ششده" },
  { provinceId: "71", label: "مزایجان" },
  { provinceId: "71", label: "ایج" },
  { provinceId: "71", label: "خور" },
  { provinceId: "71", label: "نوجین" },
  { provinceId: "71", label: "لپویی" },
  { provinceId: "71", label: "بهمن" },
  { provinceId: "71", label: "اهل" },
  { provinceId: "71", label: "خشت" },
  { provinceId: "71", label: "مهر" },
  { provinceId: "71", label: "جنت شهر" },
  { provinceId: "71", label: "مشکان" },
  { provinceId: "71", label: "بالاده" },
  { provinceId: "71", label: "قیر" },
  { provinceId: "71", label: "قطب آباد" },
  { provinceId: "71", label: "خانیمن" },
  { provinceId: "71", label: "مصیری" },
  { provinceId: "71", label: "میانشهر" },
  { provinceId: "71", label: "صفاشهر" },
  { provinceId: "71", label: "اقلید" },
  { provinceId: "71", label: "عمادده" },
  { provinceId: "71", label: "مادرسلیمان" },
  { provinceId: "71", label: "داریان" },
  { provinceId: "71", label: "رونیز" },
  { provinceId: "71", label: "کره ای" },
  { provinceId: "71", label: "لار" },
  { provinceId: "71", label: "اسیر" },
  { provinceId: "71", label: "هماشهر" },
  { provinceId: "71", label: "آباده" },
  { provinceId: "71", label: "لامرد" },
  { provinceId: "28", label: "سگزآباد" },
  { provinceId: "28", label: "بیدستان" },
  { provinceId: "28", label: "کوهین" },
  { provinceId: "28", label: "رازمیان" },
  { provinceId: "28", label: "خرمدشت" },
  { provinceId: "28", label: "آبگرم" },
  { provinceId: "28", label: "شال" },
  { provinceId: "28", label: "شریفیه" },
  { provinceId: "28", label: "اقبالیه" },
  { provinceId: "28", label: "نرجه" },
  { provinceId: "28", label: "ارداق" },
  { provinceId: "28", label: "الوند" },
  { provinceId: "28", label: "خاکعلی" },
  { provinceId: "28", label: "سیردان" },
  { provinceId: "28", label: "ضیاڈآباد" },
  { provinceId: "28", label: "بویین زهرا" },
  { provinceId: "28", label: "محمدیه" },
  { provinceId: "28", label: "محمودآبادنمونه" },
  { provinceId: "28", label: "معلم کلایه" },
  { provinceId: "28", label: "اسفرورین" },
  { provinceId: "28", label: "آوج" },
  { provinceId: "28", label: "دانسفهان" },
  { provinceId: "28", label: "آبیک" },
  { provinceId: "28", label: "قزوین" },
  { provinceId: "28", label: "تاکستان" },
  { provinceId: "25", label: "کهک" },
  { provinceId: "25", label: "قم" },
  { provinceId: "25", label: "سلفچگان" },
  { provinceId: "25", label: "جعفریه" },
  { provinceId: "25", label: "قنوات" },
  { provinceId: "25", label: "دستجرد" },
  { provinceId: "87", label: "قروه" },
  { provinceId: "87", label: "توپ آغاج" },
  { provinceId: "87", label: "سروآباد" },
  { provinceId: "87", label: "بویین سفلی" },
  { provinceId: "87", label: "زرینه" },
  { provinceId: "87", label: "دلبران" },
  { provinceId: "87", label: "سنندج" },
  { provinceId: "87", label: "یاسوکند" },
  { provinceId: "87", label: "موچش" },
  { provinceId: "87", label: "بانه" },
  { provinceId: "87", label: "مریوان" },
  { provinceId: "87", label: "سریش آباد" },
  { provinceId: "87", label: "صاحب" },
  { provinceId: "87", label: "دهگلان" },
  { provinceId: "87", label: "بابارشانی" },
  { provinceId: "87", label: "دیواندره" },
  { provinceId: "87", label: "برده رشه" },
  { provinceId: "87", label: "شویشه" },
  { provinceId: "87", label: "بیجار" },
  { provinceId: "87", label: "اورامان تخت" },
  { provinceId: "87", label: "کانی سور" },
  { provinceId: "87", label: "کانی دینار" },
  { provinceId: "87", label: "دزج" },
  { provinceId: "87", label: "سقز" },
  { provinceId: "87", label: "بلبان آباد" },
  { provinceId: "87", label: "پیرتاج" },
  { provinceId: "87", label: "کامیاران" },
  { provinceId: "87", label: "آرمرده" },
  { provinceId: "87", label: "چناره" },
  { provinceId: "34", label: "کهنوج" },
  { provinceId: "34", label: "بلوک" },
  { provinceId: "34", label: "پاریز" },
  { provinceId: "34", label: "گنبکی" },
  { provinceId: "34", label: "زنگی آباد" },
  { provinceId: "34", label: "بم" },
  { provinceId: "34", label: "خانوک" },
  { provinceId: "34", label: "کیانشهر" },
  { provinceId: "34", label: "جوپار" },
  { provinceId: "34", label: "عنبرآباد" },
  { provinceId: "34", label: "جوزم" },
  { provinceId: "34", label: "نظام شهر" },
  { provinceId: "34", label: "لاله زار" },
  { provinceId: "34", label: "کشکوییه" },
  { provinceId: "34", label: "زیدآباد" },
  { provinceId: "34", label: "هنزا" },
  { provinceId: "34", label: "چترود" },
  { provinceId: "34", label: "جبالبارز" },
  { provinceId: "34", label: "سیرجان" },
  { provinceId: "34", label: "رودبار" },
  { provinceId: "34", label: "کرمان" },
  { provinceId: "34", label: "بافت" },
  { provinceId: "34", label: "صفاییه" },
  { provinceId: "34", label: "منوجان" },
  { provinceId: "34", label: "اندوهجرد" },
  { provinceId: "34", label: "هجدک" },
  { provinceId: "34", label: "خورسند" },
  { provinceId: "34", label: "امین شهر" },
  { provinceId: "34", label: "بردسیر" },
  { provinceId: "34", label: "رفسنجان" },
  { provinceId: "34", label: "هماشهر" },
  { provinceId: "34", label: "محمدآباد" },
  { provinceId: "34", label: "اختیارآباد" },
  { provinceId: "34", label: "بروات" },
  { provinceId: "34", label: "ریحان" },
  { provinceId: "34", label: "کوهبنان" },
  { provinceId: "34", label: "ماهان" },
  { provinceId: "34", label: "دوساری" },
  { provinceId: "34", label: "دهج" },
  { provinceId: "34", label: "فاریاب" },
  { provinceId: "34", label: "گلزار" },
  { provinceId: "34", label: "بهرمان" },
  { provinceId: "34", label: "بلورد" },
  { provinceId: "34", label: "فهرج" },
  { provinceId: "34", label: "کاظم آباد" },
  { provinceId: "34", label: "جیرفت" },
  { provinceId: "34", label: "نجف شهر" },
  { provinceId: "34", label: "قلعه گنج" },
  { provinceId: "34", label: "باغین" },
  { provinceId: "34", label: "بزنجان" },
  { provinceId: "34", label: "زرند" },
  { provinceId: "34", label: "نودژ" },
  { provinceId: "34", label: "گلباف" },
  { provinceId: "34", label: "راور" },
  { provinceId: "34", label: "خاتون اباد" },
  { provinceId: "34", label: "نرماشیر" },
  { provinceId: "34", label: "دشتکار" },
  { provinceId: "34", label: "مس سرچشمه" },
  { provinceId: "34", label: "خواجو شهر" },
  { provinceId: "34", label: "رابر" },
  { provinceId: "34", label: "راین" },
  { provinceId: "34", label: "درب بهشت" },
  { provinceId: "34", label: "یزدان شهر" },
  { provinceId: "34", label: "زهکلوت" },
  { provinceId: "34", label: "محی آباد" },
  { provinceId: "34", label: "مردهک" },
  { provinceId: "34", label: "شهداد" },
  { provinceId: "34", label: "ارزوییه" },
  { provinceId: "34", label: "نگار" },
  { provinceId: "34", label: "شهربابک" },
  { provinceId: "34", label: "انار" },
  { provinceId: "83", label: "سنقر" },
  { provinceId: "83", label: "شاهو" },
  { provinceId: "83", label: "بانوره" },
  { provinceId: "83", label: "تازه آباد" },
  { provinceId: "83", label: "هلشی" },
  { provinceId: "83", label: "جوانرود" },
  { provinceId: "83", label: "قصرشیرین" },
  { provinceId: "83", label: "نوسود" },
  { provinceId: "83", label: "کرند" },
  { provinceId: "83", label: "کوزران" },
  { provinceId: "83", label: "بیستون" },
  { provinceId: "83", label: "حمیل" },
  { provinceId: "83", label: "گیلانغرب" },
  { provinceId: "83", label: "سطر" },
  { provinceId: "83", label: "روانسر" },
  { provinceId: "83", label: "پاوه" },
  { provinceId: "83", label: "ازگله" },
  { provinceId: "83", label: "کرمانشاه" },
  { provinceId: "83", label: "میان راهان" },
  { provinceId: "83", label: "کنگاور" },
  { provinceId: "83", label: "سرپل ذهاب" },
  { provinceId: "83", label: "ریجاب" },
  { provinceId: "83", label: "باینگان" },
  { provinceId: "83", label: "هرسین" },
  { provinceId: "83", label: "اسلام آبادغرب" },
  { provinceId: "83", label: "سرمست" },
  { provinceId: "83", label: "سومار" },
  { provinceId: "83", label: "نودشه" },
  { provinceId: "83", label: "گهواره" },
  { provinceId: "83", label: "رباط" },
  { provinceId: "83", label: "صحنه" },
  { provinceId: "83", label: "گودین" },
  { provinceId: "74", label: "گراب سفلی" },
  { provinceId: "74", label: "لنده" },
  { provinceId: "74", label: "سی سخت" },
  { provinceId: "74", label: "دهدشت" },
  { provinceId: "74", label: "یاسوج" },
  { provinceId: "74", label: "سرفاریاب" },
  { provinceId: "74", label: "دوگنبدان" },
  { provinceId: "74", label: "چیتاب" },
  { provinceId: "74", label: "لیکک" },
  { provinceId: "74", label: "دیشموک" },
  { provinceId: "74", label: "مادوان" },
  { provinceId: "74", label: "باشت" },
  { provinceId: "74", label: "پاتاوه" },
  { provinceId: "74", label: "قلعه رییسی" },
  { provinceId: "74", label: "مارگون" },
  { provinceId: "74", label: "چرام" },
  { provinceId: "74", label: "سوق" },
  { provinceId: "17", label: "سیمین شهر" },
  { provinceId: "17", label: "مزرعه" },
  { provinceId: "17", label: "رامیان" },
  { provinceId: "17", label: "فراغی" },
  { provinceId: "17", label: "گنبدکاووس" },
  { provinceId: "17", label: "کردکوی" },
  { provinceId: "17", label: "مراوه" },
  { provinceId: "17", label: "بندرترکمن" },
  { provinceId: "17", label: "نگین شهر" },
  { provinceId: "17", label: "آق قلا" },
  { provinceId: "17", label: "سرخنکلاته" },
  { provinceId: "17", label: "گالیکش" },
  { provinceId: "17", label: "سنگدوین" },
  { provinceId: "17", label: "دلند" },
  { provinceId: "17", label: "بندرگز" },
  { provinceId: "17", label: "نوده خاندوز" },
  { provinceId: "17", label: "مینودشت" },
  { provinceId: "17", label: "گرگان" },
  { provinceId: "17", label: "گمیش تپه" },
  { provinceId: "17", label: "علی اباد" },
  { provinceId: "17", label: "خان ببین" },
  { provinceId: "17", label: "کلاله" },
  { provinceId: "17", label: "اینچه برون" },
  { provinceId: "17", label: "فاضل آباد" },
  { provinceId: "17", label: "تاتارعلیا" },
  { provinceId: "17", label: "نوکنده" },
  { provinceId: "17", label: "آزادشهر" },
  { provinceId: "17", label: "انبارآلوم" },
  { provinceId: "17", label: "جلین" },
  { provinceId: "13", label: "منجیل" },
  { provinceId: "13", label: "شلمان" },
  { provinceId: "13", label: "خشکبیجار" },
  { provinceId: "13", label: "ماکلوان" },
  { provinceId: "13", label: "سنگر" },
  { provinceId: "13", label: "مرجقل" },
  { provinceId: "13", label: "لیسار" },
  { provinceId: "13", label: "رضوانشهر" },
  { provinceId: "13", label: "رحیم آباد" },
  { provinceId: "13", label: "لوندویل" },
  { provinceId: "13", label: "احمدسرگوراب" },
  { provinceId: "13", label: "لوشان" },
  { provinceId: "13", label: "اطاقور" },
  { provinceId: "13", label: "لشت نشاء" },
  { provinceId: "13", label: "فومن" },
  { provinceId: "13", label: "چوبر" },
  { provinceId: "13", label: "بازار جمعه" },
  { provinceId: "13", label: "کلاچای" },
  { provinceId: "13", label: "بندرانزلی" },
  { provinceId: "13", label: "املش" },
  { provinceId: "13", label: "رستم آباد" },
  { provinceId: "13", label: "لاهیجان" },
  { provinceId: "13", label: "توتکابن" },
  { provinceId: "13", label: "لنگرود" },
  { provinceId: "13", label: "کوچصفهان" },
  { provinceId: "13", label: "صومعه سرا" },
  { provinceId: "13", label: "اسالم" },
  { provinceId: "13", label: "دیلمان" },
  { provinceId: "13", label: "رودسر" },
  { provinceId: "13", label: "کیاشهر" },
  { provinceId: "13", label: "شفت" },
  { provinceId: "13", label: "رودبار" },
  { provinceId: "13", label: "کومله" },
  { provinceId: "13", label: "رشت" },
  { provinceId: "13", label: "ماسوله" },
  { provinceId: "13", label: "خمام" },
  { provinceId: "13", label: "ماسال" },
  { provinceId: "13", label: "واجارگاه" },
  { provinceId: "13", label: "هشتپر (تالش)" },
  { provinceId: "13", label: "پره سر" },
  { provinceId: "13", label: "بره سر" },
  { provinceId: "13", label: "آستارا" },
  { provinceId: "13", label: "رودبنه" },
  { provinceId: "13", label: "جیرنده" },
  { provinceId: "13", label: "چاف و چمخاله" },
  { provinceId: "13", label: "لولمان" },
  { provinceId: "13", label: "گوراب زرمیخ" },
  { provinceId: "13", label: "حویق" },
  { provinceId: "13", label: "سیاهکل" },
  { provinceId: "13", label: "چابکسر" },
  { provinceId: "13", label: "آستانه اشرفیه" },
  { provinceId: "13", label: "رانکوه" },
  { provinceId: "66", label: "چالانچولان" },
  { provinceId: "66", label: "بیران شهر" },
  { provinceId: "66", label: "ویسیان" },
  { provinceId: "66", label: "شول آباد" },
  { provinceId: "66", label: "پلدختر" },
  { provinceId: "66", label: "کوهدشت" },
  { provinceId: "66", label: "هفت چشمه" },
  { provinceId: "66", label: "بروجرد" },
  { provinceId: "66", label: "الشتر" },
  { provinceId: "66", label: "مومن آباد" },
  { provinceId: "66", label: "دورود" },
  { provinceId: "66", label: "زاغه" },
  { provinceId: "66", label: "چقابل" },
  { provinceId: "66", label: "الیگودرز" },
  { provinceId: "66", label: "معمولان" },
  { provinceId: "66", label: "کوهنانی" },
  { provinceId: "66", label: "نورآباد" },
  { provinceId: "66", label: "سپیددشت" },
  { provinceId: "66", label: "سراب دوره" },
  { provinceId: "66", label: "ازنا" },
  { provinceId: "66", label: "گراب" },
  { provinceId: "66", label: "خرم آباد" },
  { provinceId: "66", label: "اشترینان" },
  { provinceId: "66", label: "فیروزآباد" },
  { provinceId: "66", label: "درب گنبد" },
  { provinceId: "11", label: "گلوگاه" },
  { provinceId: "11", label: "گلوگاه" },
  { provinceId: "11", label: "پل سفید" },
  { provinceId: "11", label: "دابودشت" },
  { provinceId: "11", label: "چالوس" },
  { provinceId: "11", label: "کیاسر" },
  { provinceId: "11", label: "بهنمیر" },
  { provinceId: "11", label: "تنکابن" },
  { provinceId: "11", label: "کلاردشت" },
  { provinceId: "11", label: "ایزدشهر" },
  { provinceId: "11", label: "گتاب" },
  { provinceId: "11", label: "سلمان شهر" },
  { provinceId: "11", label: "ارطه" },
  { provinceId: "11", label: "امیرکلا" },
  { provinceId: "11", label: "کوهی خیل" },
  { provinceId: "11", label: "پایین هولار" },
  { provinceId: "11", label: "گزنک" },
  { provinceId: "11", label: "محمودآباد" },
  { provinceId: "11", label: "رامسر" },
  { provinceId: "11", label: "نوشهر" },
  { provinceId: "11", label: "خلیل شهر" },
  { provinceId: "11", label: "کیاکلا" },
  { provinceId: "11", label: "نور" },
  { provinceId: "11", label: "مرزیکلا" },
  { provinceId: "11", label: "فریدونکنار" },
  { provinceId: "11", label: "زیرآب" },
  { provinceId: "11", label: "امامزاده عبدالله" },
  { provinceId: "11", label: "هچیرود" },
  { provinceId: "11", label: "فریم" },
  { provinceId: "11", label: "هادی شهر" },
  { provinceId: "11", label: "نشتارود" },
  { provinceId: "11", label: "پول" },
  { provinceId: "11", label: "بهشهر" },
  { provinceId: "11", label: "کلارآباد" },
  { provinceId: "11", label: "بلده" },
  { provinceId: "11", label: "بابل" },
  { provinceId: "11", label: "جویبار" },
  { provinceId: "11", label: "آلاشت" },
  { provinceId: "11", label: "آمل" },
  { provinceId: "11", label: "نکا" },
  { provinceId: "11", label: "کتالم وسادات شهر" },
  { provinceId: "11", label: "بابلسر" },
  { provinceId: "11", label: "شیرود" },
  { provinceId: "11", label: "شیرگاه" },
  { provinceId: "11", label: "رویان" },
  { provinceId: "11", label: "زرگرمحله" },
  { provinceId: "11", label: "عباس اباد" },
  { provinceId: "11", label: "قایم شهر" },
  { provinceId: "11", label: "خوش رودپی" },
  { provinceId: "11", label: "مرزن آباد" },
  { provinceId: "11", label: "ساری" },
  { provinceId: "11", label: "رینه" },
  { provinceId: "11", label: "سرخرود" },
  { provinceId: "11", label: "خرم آباد" },
  { provinceId: "11", label: "کجور" },
  { provinceId: "11", label: "رستمکلا" },
  { provinceId: "11", label: "سورک" },
  { provinceId: "11", label: "چمستان" },
  { provinceId: "86", label: "آستانه" },
  { provinceId: "86", label: "خنجین" },
  { provinceId: "86", label: "نراق" },
  { provinceId: "86", label: "کمیجان" },
  { provinceId: "86", label: "آشتیان" },
  { provinceId: "86", label: "رازقان" },
  { provinceId: "86", label: "مهاجران" },
  { provinceId: "86", label: "غرق آباد" },
  { provinceId: "86", label: "خنداب" },
  { provinceId: "86", label: "قورچی باشی" },
  { provinceId: "86", label: "خشکرود" },
  { provinceId: "86", label: "ساروق" },
  { provinceId: "86", label: "محلات" },
  { provinceId: "86", label: "شازند" },
  { provinceId: "86", label: "ساوه" },
  { provinceId: "86", label: "میلاجرد" },
  { provinceId: "86", label: "تفرش" },
  { provinceId: "86", label: "زاویه" },
  { provinceId: "86", label: "اراک" },
  { provinceId: "86", label: "توره" },
  { provinceId: "86", label: "نوبران" },
  { provinceId: "86", label: "فرمهین" },
  { provinceId: "86", label: "دلیجان" },
  { provinceId: "86", label: "پرندک" },
  { provinceId: "86", label: "کارچان" },
  { provinceId: "86", label: "نیمور" },
  { provinceId: "86", label: "هندودر" },
  { provinceId: "86", label: "آوه" },
  { provinceId: "86", label: "جاورسیان" },
  { provinceId: "86", label: "خمین" },
  { provinceId: "86", label: "مامونیه" },
  { provinceId: "86", label: "داودآباد" },
  { provinceId: "86", label: "شهباز" },
  { provinceId: "76", label: "بیکاء" },
  { provinceId: "76", label: "تیرور" },
  { provinceId: "76", label: "گروک" },
  { provinceId: "76", label: "قشم" },
  { provinceId: "76", label: "کوشکنار" },
  { provinceId: "76", label: "کیش" },
  { provinceId: "76", label: "سرگز" },
  { provinceId: "76", label: "بندرعباس" },
  { provinceId: "76", label: "زیارتعلی" },
  { provinceId: "76", label: "سندرک" },
  { provinceId: "76", label: "کوهستک" },
  { provinceId: "76", label: "لمزان" },
  { provinceId: "76", label: "رویدر" },
  { provinceId: "76", label: "قلعه قاضی" },
  { provinceId: "76", label: "فارغان" },
  { provinceId: "76", label: "ابوموسی" },
  { provinceId: "76", label: "هشتبندی" },
  { provinceId: "76", label: "سردشت" },
  { provinceId: "76", label: "درگهان" },
  { provinceId: "76", label: "پارسیان" },
  { provinceId: "76", label: "کنگ" },
  { provinceId: "76", label: "جناح" },
  { provinceId: "76", label: "تازیان پایین" },
  { provinceId: "76", label: "دهبارز" },
  { provinceId: "76", label: "میناب" },
  { provinceId: "76", label: "سیریک" },
  { provinceId: "76", label: "سوزا" },
  { provinceId: "76", label: "خمیر" },
  { provinceId: "76", label: "چارک" },
  { provinceId: "76", label: "حاجی اباد" },
  { provinceId: "76", label: "فین" },
  { provinceId: "76", label: "بندرجاسک" },
  { provinceId: "76", label: "گوهران" },
  { provinceId: "76", label: "هرمز" },
  { provinceId: "76", label: "دشتی" },
  { provinceId: "76", label: "بندرلنگه" },
  { provinceId: "76", label: "بستک" },
  { provinceId: "76", label: "تخت" },
  { provinceId: "81", label: "زنگنه" },
  { provinceId: "81", label: "دمق" },
  { provinceId: "81", label: "سرکان" },
  { provinceId: "81", label: "آجین" },
  { provinceId: "81", label: "جورقان" },
  { provinceId: "81", label: "برزول" },
  { provinceId: "81", label: "فامنین" },
  { provinceId: "81", label: "سامن" },
  { provinceId: "81", label: "بهار" },
  { provinceId: "81", label: "فرسفج" },
  { provinceId: "81", label: "شیرین سو" },
  { provinceId: "81", label: "مریانج" },
  { provinceId: "81", label: "فیروزان" },
  { provinceId: "81", label: "قروه درجزین" },
  { provinceId: "81", label: "ازندریان" },
  { provinceId: "81", label: "لالجین" },
  { provinceId: "81", label: "گل تپه" },
  { provinceId: "81", label: "گیان" },
  { provinceId: "81", label: "ملایر" },
  { provinceId: "81", label: "صالح آباد" },
  { provinceId: "81", label: "تویسرکان" },
  { provinceId: "81", label: "اسدآباد" },
  { provinceId: "81", label: "همدان" },
  { provinceId: "81", label: "نهاوند" },
  { provinceId: "81", label: "رزن" },
  { provinceId: "81", label: "جوکار" },
  { provinceId: "81", label: "مهاجران" },
  { provinceId: "81", label: "کبودرآهنگ" },
  { provinceId: "81", label: "قهاوند" },
  { provinceId: "35", label: "مروست" },
  { provinceId: "35", label: "مهردشت" },
  { provinceId: "35", label: "حمیدیا" },
  { provinceId: "35", label: "تفت" },
  { provinceId: "35", label: "اشکذر" },
  { provinceId: "35", label: "ندوشن" },
  { provinceId: "35", label: "یزد" },
  { provinceId: "35", label: "عقدا" },
  { provinceId: "35", label: "بهاباد" },
  { provinceId: "35", label: "ابرکوه" },
  { provinceId: "35", label: "زارچ" },
  { provinceId: "35", label: "نیر" },
  { provinceId: "35", label: "اردکان" },
  { provinceId: "35", label: "هرات" },
  { provinceId: "35", label: "بفروییه" },
  { provinceId: "35", label: "شاهدیه" },
  { provinceId: "35", label: "بافق" },
  { provinceId: "35", label: "خضرآباد" },
  { provinceId: "35", label: "میبد" },
  { provinceId: "35", label: "مهریز" },
  { provinceId: "35", label: "احمدآباد" },
  { provinceId: "0", label: "خارج از کشور" }]
  const provinces = [
    { value: "21", label: "تهران" },
    { value: "0", label: "خارج از کشور" },
    { value: "41", label: "آذربایجان شرقی" },
    { value: "44", label: "آذربایجان غربی" },
    { value: "45", label: "اردبیل" },
    { value: "31", label: "اصفهان" },
    { value: "26", label: "البرز" },
    { value: "84", label: "ایلام" },
    { value: "77", label: "بوشهر" },
    { value: "38", label: "چهارمحال و بختیاری" },
    { value: "56", label: "خراسان جنوبی" },
    { value: "51", label: "خراسان رضوی" },
    { value: "58", label: "خراسان شمالی" },
    { value: "61", label: "خوزستان" },
    { value: "24", label: "زنجان" },
    { value: "23", label: "سمنان" },
    { value: "54", label: "سیستان و بلوچستان" },
    { value: "71", label: "فارس" },
    { value: "28", label: "قزوین" },
    { value: "25", label: "قم" },
    { value: "17", label: "گلستان" },
    { value: "13", label: "گیلان" },
    { value: "66", label: "لرستان" },
    { value: "11", label: "مازندران" },
    { value: "86", label: "مرکزی" },
    { value: "76", label: "هرمزگان" },
    { value: "81", label: "همدان" },
    { value: "87", label: "کردستان" },
    { value: "34", label: "کرمان" },
    { value: "83", label: "کرمانشاه" },
    { value: "74", label: "کهگیلویه وبویراحمد" },
    { value: "35", label: "یزد" }] as OptionType[]

  const EcommerceAccountPersonalSchema = Yup.object().shape({
    fullname: Yup.string().required('نام و نام خانوادگی الزامیست.'),
  })

  const defaultValues = {
    fullname: '',
    companyName: '',
    jobTitle: '',
    gender: { value: '', label: 'انتخاب نشده' } as OptionType,
    province: { value: '', label: 'انتخاب نشده' } as OptionType,
    city: { value: '', label: 'انتخاب نشده' } as OptionType,
    year: { value: '', label: 'انتخاب نشده' } as OptionType,
    month: { value: '', label: 'انتخاب نشده' } as OptionType,
    day: { value: '', label: 'انتخاب نشده' } as OptionType,
  }

  const methods = useForm<typeof defaultValues>({
    resolver: yupResolver(EcommerceAccountPersonalSchema),
    defaultValues,
  })

  const {
    handleSubmit,
    setValue,
    watch,
    getValues,
    formState: { isSubmitting },
  } = methods

  useEffect(() => {
    const newcities = cities.filter(t => t.provinceId === (getValues('province') as any as OptionType)?.value).map(t => ({ label: t.label, value: t.label }))

    setFilteredCities(newcities)
  }
    , [watch('province')])
  const onSubmit = async (data: typeof defaultValues) => {
    console.log(data)
    setInfo({ setInfoModel: data }).unwrap().then(() => {
      notify({ type: 'success', message: "اطلاعات شما با موفقیت ذخیره شد" })
    })
  }

  useEffect(() => {
    if (dataInfo) {
      setValue('fullname', dataInfo?.fullname as string)
      setValue('companyName', dataInfo.companyName as string)
      setValue('jobTitle', dataInfo.jobTitle as string)
      if (dataInfo.province) {
        setValue('province', provinces.find(t => t.label == dataInfo.province) as OptionType)
      }
      if (dataInfo.city) {
        const city = cities.find(t => t.label == dataInfo.city)
        setValue('city', { value: city?.label, label: city?.label } as OptionType)
      }
      if (dataInfo?.birthDate) {
        const birthDate = dayjs(dataInfo?.birthDate).calendar('jalali')

        setValue('year', { value: birthDate.format('YYYY'), label: birthDate.format('YYYY') } as OptionType)
        setValue('month', { value: birthDate.format('MM'), label: birthDate.format('MM') } as OptionType)
        setValue('day', { value: birthDate.format('DD'), label: birthDate.format('DD') } as OptionType)
      }
      if (dataInfo?.gender != null)
        setValue('gender', { value: dataInfo.gender ? "1" : "0", label: dataInfo.gender ? "مرد" : "زن" } as OptionType)
    }
  }, [dataInfo])

  useEffect(() => {
    getInfo()
  }, [])

  useEffect(() => {
    if (!accessToken) {
      push('/')
      return
    }
  }, [accessToken])

  return (
    <EcommerceAccountLayout>
      <FormProvider methods={methods} onSubmit={handleSubmit(onSubmit)}>
        <Typography variant='h5' sx={{ mb: 3 }}>
          {intl.formatMessage({ id: 'personal.info' })}
        </Typography>
        <Box
          rowGap={2.5}
          columnGap={2}
          display='grid'
          gridTemplateColumns={{ xs: 'repeat(1, 1fr)', md: 'repeat(5, 1fr)' }}
        >

          <RHFTextField name='fullname' label={intl.formatMessage({ id: 'personal.info.name' })} />
          <RHFTextField name='companyName' label={intl.formatMessage({ id: 'personal.info.job' })} />
          <RHFTextField name='jobTitle' label={intl.formatMessage({ id: 'personal.info.company' })} />

          <RHFAutocomplete

            name='gender'
            label='جنسیت'
            options={[
              { value: '', label: 'انتخاب نشده' },
              { value: '0', label: 'زن' },
              { value: '1', label: 'مرد' },
            ]}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            }
          />

        </Box>

        <Box
          rowGap={2.5}
          columnGap={2.5}
          style={{ marginTop: "1rem" ,marginBottom:"1.5rem"}}
          display='grid'
          gridTemplateColumns={{ xs: 'repeat(1, 1fr)', md: 'repeat(5, 1fr)' }}
        >
          <RHFAutocomplete
            name='province'
            label='استان'
            options={provinces}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            }
          />
          <RHFAutocomplete
            name='city'
            label='شهر'
            options={filteredCities}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            } />
        </Box>
        <Typography variant='h5' sx={{ mb: 3 }}>
          تاریخ تولد
        </Typography>
        <Stack spacing={2.5} sx={{ width: 1 }} direction={{ xs: "column", md: "row" }} >
          <RHFAutocomplete
            name='day'
            label='روز'
            options={Array.from({ length: 31 }, (_, index) => 1 + index).map((i) => ({ label: `${i}`, value: `${i}` } as OptionType))}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            }
          />
          <RHFAutocomplete
            name='month'
            label='ماه'
            options={Array.from({ length: 12 }, (_, index) => 1 + index).map((i) => ({ label: `${i}`, value: `${i}` } as OptionType))}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            }
          />
          <RHFAutocomplete
            name='year'
            label='سال'
            sx={{ width: { md: '120px', xs: "100%" } }}
            options={Array.from({ length: 92 }, (_, index) => 1392 - index).map((i) => ({ label: `${i}`, value: `${i}` } as OptionType))}
            getOptionLabel={(option: OptionType | string) =>
              (option as OptionType).label as string
            }
            isOptionEqualToValue={(option, value) =>
              option.value === value.value
            }
          />
        </Stack>
        <LoadingButton
          color='inherit'
          size='large'
          type='submit'
          variant='contained'
          loading={isLoading}
          sx={{ marginBlockStart: '3rem' }}
        >
          {intl.formatMessage({ id: 'save' })}
        </LoadingButton>
      </FormProvider>
    </EcommerceAccountLayout >
  )
}

export default EcommerceAccountPersonalView
